 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/facebook_videos", type: :request do
  # FacebookVideo. As you add validations to FacebookVideo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FacebookVideo.create! valid_attributes
      get facebook_videos_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      facebook_video = FacebookVideo.create! valid_attributes
      get facebook_video_url(facebook_video)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_facebook_video_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      facebook_video = FacebookVideo.create! valid_attributes
      get edit_facebook_video_url(facebook_video)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FacebookVideo" do
        expect {
          post facebook_videos_url, params: { facebook_video: valid_attributes }
        }.to change(FacebookVideo, :count).by(1)
      end

      it "redirects to the created facebook_video" do
        post facebook_videos_url, params: { facebook_video: valid_attributes }
        expect(response).to redirect_to(facebook_video_url(FacebookVideo.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FacebookVideo" do
        expect {
          post facebook_videos_url, params: { facebook_video: invalid_attributes }
        }.to change(FacebookVideo, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post facebook_videos_url, params: { facebook_video: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested facebook_video" do
        facebook_video = FacebookVideo.create! valid_attributes
        patch facebook_video_url(facebook_video), params: { facebook_video: new_attributes }
        facebook_video.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the facebook_video" do
        facebook_video = FacebookVideo.create! valid_attributes
        patch facebook_video_url(facebook_video), params: { facebook_video: new_attributes }
        facebook_video.reload
        expect(response).to redirect_to(facebook_video_url(facebook_video))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        facebook_video = FacebookVideo.create! valid_attributes
        patch facebook_video_url(facebook_video), params: { facebook_video: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested facebook_video" do
      facebook_video = FacebookVideo.create! valid_attributes
      expect {
        delete facebook_video_url(facebook_video)
      }.to change(FacebookVideo, :count).by(-1)
    end

    it "redirects to the facebook_videos list" do
      facebook_video = FacebookVideo.create! valid_attributes
      delete facebook_video_url(facebook_video)
      expect(response).to redirect_to(facebook_videos_url)
    end
  end
end
